### PR TITLE
more tests

### PR DESCRIPTION
**Pull request by siudej**
- Added more tests.
- All data sets now return sqdist and points.
- One issue: circle graph does not work as it should. Is it needed?
- metricize2 passes all tests and gives the same results as metricize3. But maybe just for me.

### CODE REVIEW

**Comment by micah541** [comment]
I'm still getting weird results with metricize2

**Comment by siudej** [comment]
Can you try running tools.py as the main script? You should get some test results.

**Comment by micah541** [comment]
I'm getting FAIL

**Comment by siudej** [comment]
It could be different Anaconda version. Or maybe the tests will run ok, meaning they are not good enough.

**Comment by siudej** [comment]
I just tried running localricci with metricize2 and the moons where recognized.

I have updated my Anaconda to 2.5 recently.

**Pull request merged**
