### PR TITLE
Plotting

### PR DESCRIPTION
**Pull request by siudej**
- Show growing clusters as intermediate steps. Can be colored by cluster name, or distance to a chosen point. Also prints distances between clusters.
- Started temporary matrix management. All functions should request appropriate number of temporary matrices from the pool created in the main script. Ricci still uses too much memory. Laplacian must be optimized too.
- Added C++ connected components function to aid plotting clusters.
- `localricci.py` runs until just to components are left. This should change to until clustered and/or a number of components. Perhaps we should have a function that checks a series of conditions.

### CODE REVIEW

**Comment by micah541** [comment]
I have a satisfactory answer from a pure math point of view:

Define the d = sup of all functions satisfying the triangle inequality 
and below d*.   This defines a metric.
Implementing it might take something, but at least the object is well 
defined.

**Comment by micah541** [comment]
I think this is a linear programming problem with a fuck ton of constrains.

**Comment by siudej** [comment]
I agree,. With n^3 constraints, so way too much memory needed.

We will need to settle on some approximate scheme, hopefully not collapsing to degenerate distance.

**Comment by micah541** [comment]
Smacof.    I ran into Sam.  Scaling by Majorizing a complicated function.

**Pull request merged**
